# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WSUuO6mu5UdON1VnDhgTZmmS-bu9IJqR
"""

temperatura = 30

if temperatura <= 27:
  print("esta um dia agradavel")
else:
  print("esta quente socorro")

idade = 14

if idade  >= 18 :
  print("voce é maior de idade")
else:
  print("voce ainda é menor de idade")



nome = "darcio jr"


if nome == "darcio jr":
  print("melhor pai do mundo")
elif nome =="darcio pai":
  print("melhor avo do mundo")
else:
  print("vc é um pai ou avo comum")

frio  = False
gosta_de_frio = False

if frio == True:
    print("esta frio")
    if gosta_de_frio == False:
      print("que pena que esta frio")
    elif gosta_de_frio == True:
       print("aproveite esse dia")

elif frio == False:
  print("esta calor")

# genios que mudaram ou vao mudar o mundo s2

nome = "Einstein"

if nome == "Newton":
  print("infelizmente newton ja foi dessa para uma melhor ")
if nome == "Einstein":
  print("infelizmente Einstein ja foi dessa para uma melhor")
elif nome == "Zarkcy":
   print("esse genio ainda esta vivo e vai mudar o mundo")
melhor prof

